//==============================================================================
//          -- > Error Message Defines
//==============================================================================
#define ERROR_LOGGEDIN															"You are not logged in, mate."
#define ERROR_ADMIN 															"You don't have access to this command."
#define ERROR_SPAM_TIME															"This command cannot be performed at this point in time."
#define ERROR_LOCATION															"This command cannot be performed at this location."
#define ERROR_MONEY																"Insufficient funds."
#define ERROR_ADMINLEVEL														"This cannot be performed on a higher level administrator."
#define ERROR_INVALIDPLAYER														"Invalid player specified."
#define ERROR_VEHICLE															"You must be in a vehicle to perform this command."
#define ERROR_FACTION 															"You don't have access to this command."
#define ERROR_VALUE																"You cannot use that value at this point in time."
#define ERROR_OPTION															"Not a valid option."
#define ERROR_DIALOG															"The dialog has been closed."
#define ERROR_RANK																"Not a high enough rank."
#define ERROR_MUTED																"You are muted, you cannot talk."
#define ERROR_OWNED																"You already own an item of this type."
#define ERROR_OWNER																"This item is already owned."
#define ERROR_NOTOWNED															"You do not own this item."
#define ERROR_JOB																"You don't have the job required to do this."
#define ERROR_CONNECTED															"The player that you are requesting isn't connected."